# Default values for multus-thick.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  # -- Repository for the Multus image.
  repository: ghcr.io/k8snetworkplumbingwg/multus-cni
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # -- Tag of the Multus image.
  tag: "snapshot-thick"

serviceAccount:
  name: multus-thick

# -- Resources for the Multus pod.
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "100m"
    memory: "50Mi"

# -- Toleration definitions
tolerations:
  - operator: Exists
    effect: NoSchedule
  - operator: Exists
    effect: NoExecute

affinity: {}

# -- multus json config
config: |
  {
        "chrootDir": "/hostroot",
        "cniVersion": "0.3.1",
        "logLevel": "verbose",
        "logToStderr": true,
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusAutoconfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "socketDir": "/host/run/multus/"
      }
