name: Helm Charts Test

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [multus,sriov, whereabouts] # Add all your chart directories here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0' # specify the Helm version you want to use

      - name: Set up Kubernetes (kind)
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.17.0 # specify the kind version you want to use

      - name: Helm Lint
        run: helm lint ${{ matrix.chart }}

      - name: Install dependencies
        run: helm dependency update ${{ matrix.chart }}

      - name: Install Helm chart
        run: helm install --wait --timeout 60s --dry-run ${{ matrix.chart }}-release ${{ matrix.chart }}

      - name: Run Helm tests
        run: helm test ${{ matrix.chart }}-release --timeout 60s

      - name: Delete Helm release
        run: helm uninstall ${{ matrix.chart }}-release
